### ISSUE TITLE
reactor registers not being restored properly on re-entry?

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#840]
Here's a simple program with a nested reactor call:
```
include reactors

fun word-reactor():
  rw =
    reactor:
      init: "",
      on-key: 
        lam(w, k): w + k end,
    end
  interact(rw)
end

fun num-reactor():
  rn =
    reactor:
      init: 0,
      on-tick:
        lam(w) block:
          word-reactor()
          w + 1
        end,
    end
  interact(rn)
end
```
Suppose I run `num-reactor()`. After a moment, what is visible is a reactor with an empty string. Say I type a few characters, then hit Esc. This closes the string reactor and should put me back in the numeric reactor. Sure enough, I now get a reactor popup with the value 0. This makes sense; the numeric reactor is still in its initial world value. However, even after a long time this reactor's value never changes: it always stays at 0. This is despite the fact that the version of it without the call to `word-reactor` does display behavior that changes on every tick:
```
 rn =
    reactor:
      init: 0,
      on-tick:
        lam(w) block:
          w + 1
        end,
    end

interact(rn)
```
So it would appear that the `on-tick` “register” is being voided by the string reactor, but not being properly restored on return to the numeric reactor.

**Comment by jpolitz** [comment]
"ESC" doesn't mean the same thing as stop-when triggering, is what's going on.  If you add a `stop-when` and a `close-when-stop` to the string reactor (say, when the string is 5 characters long), then it works as expected.

Agree that it would be nice if this worked.

**Comment by jpolitz** [comment]
If you watch carefully when you press ESC, the prompt comes back at interactions.  Something is up with cancelling multiple levels.  @sorawee: do you have a quick guess?

**Comment by shriram** [comment]
> "ESC" doesn't mean the same thing as stop-when triggering, is what's going on. 

Sure. But I don't know where I assumed that. To me ESC just meant the string reactor wrapped up, however, and returned control to the numeric reactor. At that point, the numeric reactor should continue ticking, right? Why does the `stop-when`-ness of the string reactor have anything to do with it?

Yes, I did see the REPL return. But the numeric reactor's pop-up was still present and accepting at least the ESC.

Are you saying the ESC _also_ closed the numeric reactor? Why would it do that? I certainly didn't expect that from the program I wrote. (And if it did — if it's some sort of "throw to the top-level continuation" thing — then why was the numeric reactor's window still up?)

> If you add a stop-when and a close-when-stop to the string reactor (say, when the string is 5 characters long), then it works as expected.

I'm not sure. This is a distilled version of a much more complex program. In that program, the nested reactor has both a `stop-when` and `close-when-stop: true`. Yet I was seeing the nested reactor's value rather than the caller's (which is a very simple infinite loop, just to get around the problem of hitting Stop in a naive infinite loop).

**Comment by shriram** [comment]
I just double-checked the other program. The outer (calling, here numeric) reactor does update its state on each non-ESC return from the inner (called, here string) reactor. But, at the end of the computation, the final state is the _initial_ state of the _called_ (here string) reactor!

**Comment by jpolitz** [comment]
This program ends with the expected values:

```
include reactors

fun word-reactor():
  rw =
    reactor:
      init: "",
      close-when-stop: true,
      stop-when: lam(w): string-length(w) > 5 end,
      on-key: 
        lam(w, k): w + k end,
    end
  interact(rw)
end

fun num-reactor():
  rn =
    reactor:
      init: 0,
      stop-when: lam(w): w > 3 end,
      close-when-stop: true,
      on-tick:
        lam(w) block:
          word-reactor()
          w + 1
        end,
    end
  interact(rn)
end
```

Something's up with what "ESC" means.

**Comment by jpolitz** [comment]
Fixed by https://github.com/brownplt/code.pyret.org/commit/19a748b0121702049cd0893ac278d011ed337c42

**Comment by jpolitz** [comment]
Yeah, "ESC" meant "shutdown all interactions, return the final value of the top one on the stack, and only close the top window".  Now it just pops off one set of handlers and returns that value to the context above it, as it should.

**Comment by shriram** [comment]
Can we keep this open until this edit has been pushed to pyret-dev and I can confirm it's doing what I expect on this simple example but also in my actual program of interest?

**Comment by sorawee** [comment]
Yup, the problem is still in pyret-dev. My bad. I made a change to horizon / main CPO (https://github.com/brownplt/code.pyret.org/pull/77/files) but forgot to made change to sql. So when @jpolitz merged sql to horizon, the fix is removed.

**Comment by jpolitz** [comment]
Actually, I think I just made a mistake in the merge, and all of my tests used stop-when, rather than me manually escape-ing.

**Comment by jpolitz** [comment]
@shriram, this should work on code.pyret.org now, if you want to check.  (I had to hold ESC for a second to totally quit).

**Comment by shriram** [comment]
Joe, I'm not sure exactly what I'm supposed to be seeing, but on CPO the infinite loop doesn't stop. In fact, I even got it into a state — by pressing Esc and also clicking on Stop — to have the string reactor popup still up, responding to keys, with the rest of the screen greyed out, while the RPEL says "Program stopped by user"…

**Comment by sorawee** [comment]
@jpolitz I don't think that @shriram ever complained about CPO, and CPO should work fine since the beginning since it has my patch. What Shriram concern is pyret-dev (sql branch), which still has `shutdown` (instead of `shutdownSingle`).

**Comment by sorawee** [comment]
Oh wait... nvm, there's a problem in CPO...

**Comment by jpolitz** [comment]
@shriram, I need a better description of what's going on.  "The infinite loop doesn't stop" sounds almost like expected behavior without more detail.

**Comment by jpolitz** [comment]
This seems to work as expected for me, for both versions in this issue; it was one of the first things I tested after pushing out these changes.

**Comment by sorawee** [comment]
Confirm that both versions run as expected in CPO (though the first version has infinite loop by design).

**Comment by shriram** [comment]
Sorry, wrong bug report. 

Yes, I think it's working correctly now in that, every time I Esc out of the string reactor, the numeric reactor updates by one (a tick), then launches a new string reactor.

The fact that I got into a wedged state is still a bit troubling. What I saw was _only_ the string reactor; I wasn't seeing the numeric reactor.

But the specific issue I raised in this bug report is, I believe, corrected. Thanks.
